max_time: 13
min_time: 2
neg_weight: 0.1
spatial_drop: 0.1
structural_head_config:
- 16
- 8
structural_layer_config:
- 256
- 128
temporal_drop: 0.5
temporal_head_config:
- 16
temporal_layer_config:
- 128
