max_time: 129
min_time: 115
neg_weight: 0.01
spatial_drop: 0.1
structural_head_config:
- 16
- 8
structural_layer_config:
- 256
- 128
temporal_drop: 0.5
temporal_head_config:
- 16
temporal_layer_config:
- 128
